<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="QTP01-PC"><DocLocation><![CDATA[C:\TestAssets\QTP\GUITests\ForTestPuposes]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ForTestPuposes]]></DName>
<Res><![CDATA[Res16]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[MainTestDriver]]></AName>
<Step rID="T5">
<Obj ><![CDATA[The following Query will be Executed:  SELECT * FROM MainTable where TestCaseID in (1425)]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:31]]></Time>
<TimeTick>1440011551</TimeTick>
<NodeArgs eType="User" icon="5" nRep="8" status="Passed" Source="MainTestDriver" SourceLine="25" >
<Disp><![CDATA[The following Query will be Executed:  SELECT * FROM MainTable where TestCaseID in (1425)]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[There are 1 Records in the Main Table. ]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:34]]></Time>
<TimeTick>1440011554</TimeTick>
<NodeArgs eType="User" icon="5" nRep="9" status="Passed" Source="MainTestDriver" SourceLine="49" >
<Disp><![CDATA[There are 1 Records in the Main Table. ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[Executing Record Number 3 from the Main Table]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:34]]></Time>
<TimeTick>1440011554</TimeTick>
<NodeArgs eType="User" icon="5" nRep="10" status="Passed" Source="MainTestDriver" SourceLine="78" >
<Disp><![CDATA[Executing Record Number 3 from the Main Table]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:44]]></Time>
<TimeTick>1440011564</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:44]]></Time>
<TimeTick>1440011564</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:44]]></Time>
<TimeTick>1440011564</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="15" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Velocity Payment System ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:45]]></Time>
<TimeTick>1440011565</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="18" >
<Disp><![CDATA[[ Velocity Payment System ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ user ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:45]]></Time>
<TimeTick>1440011565</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[[ user ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ user ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["iahmed"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:45]]></Time>
<TimeTick>1440011565</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[[ user ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hello3333"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:45]]></Time>
<TimeTick>1440011565</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA[[ password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Submit ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:45]]></Time>
<TimeTick>1440011565</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" >
<Disp><![CDATA[[ Submit ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Velocity Payment System ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" >
<Disp><![CDATA[[ Velocity Payment System ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Logout ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" >
<Disp><![CDATA[[ Logout ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[  document.write(unescape('%3Cimg alt="Live chat by BoldChat" src="' + (('https:' == document.location.protocol) ? 'https:' : 'http:') + '//cbi.boldchat.com/aid/789546764707432031/bc.cbi?cbdid=4938977139570161457" border="0" /%3E'));  v+AdministratorAdd/modify/delete users • Add/modify/delete roles • Grant/revoke permissions • Manage AVS/CVV policiesAccess User Management   v+POSProcess credit card and on-line check sales • Void sales • Return salesAccess Ahmed PaymentAccess CC TestAccess Chacha Choudhry 1Access Chacha Choudhry ModAccess Cust Prof Grp TestAccess Dev 135 AppAccess Hello World3Access Imt vRelay Conv Fees3Access Imtiaz PaymentAccess New Test VRelayAccess Prod 1182 AppAccess Team India 2Access Team Pakistan 1Access Test FDMS ProcessorAccess Test New VLinkAccess Test Vital ProcessorAccess TestVRelay3.0Access VRelay_Prod_ConfigsAccess hiThere  v+ClerkMonitor payment activity • See settlement totals • View on-line check returns • Reconcile statements received from banks and card processorsAccess Email SubscriptionAccess View All Reports CSR-CustomerProvide customer support • Manage customer profiles • Pay bills and invoices • Manage voids, credits, returns and chargebacksAccess Customer Service Representative      ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="30" >
<Disp><![CDATA[[  document.write(unescape('%3Cimg alt="Live chat by BoldChat" src="' + (('https:' == document.location.protocol) ? 'https:' : 'http:') + '//cbi.boldchat.com/aid/789546764707432031/bc.cbi?cbdid=4938977139570161457" border="0" /%3E'));  v+AdministratorAdd/modify/delete users • Add/modify/delete roles • Grant/revoke permissions • Manage AVS/CVV policiesAccess User Management   v+POSProcess credit card and on-line check sales • Void sales • Return salesAccess Ahmed PaymentAccess CC TestAccess Chacha Choudhry 1Access Chacha Choudhry ModAccess Cust Prof Grp TestAccess Dev 135 AppAccess Hello World3Access Imt vRelay Conv Fees3Access Imtiaz PaymentAccess New Test VRelayAccess Prod 1182 AppAccess Team India 2Access Team Pakistan 1Access Test FDMS ProcessorAccess Test New VLinkAccess Test Vital ProcessorAccess TestVRelay3.0Access VRelay_Prod_ConfigsAccess hiThere  v+ClerkMonitor payment activity • See settlement totals • View on-line check returns • Reconcile statements received from banks and card processorsAccess Email SubscriptionAccess View All Reports CSR-CustomerProvide customer support • Manage customer profiles • Pay bills and invoices • Manage voids, credits, returns and chargebacksAccess Customer Service Representative      ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[The following Text was found on the page: Process credit card and on-line check sales]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="User" icon="5" nRep="32" status="Passed" >
<Disp><![CDATA[The following Text was found on the page: Process credit card and on-line check sales]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Batch ID: 56576]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="User" icon="5" nRep="33" status="Passed" >
<Disp><![CDATA[Batch ID: 56576]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Record found in VPO_SearchVPOS Table]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="User" icon="5" nRep="34" >
<Disp><![CDATA[Record found in VPO_SearchVPOS Table]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Access Ahmed Payment ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" >
<Disp><![CDATA[[ Access Ahmed Payment ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Access Ahmed Payment ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:48]]></Time>
<TimeTick>1440011568</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" >
<Disp><![CDATA[[ Access Ahmed Payment ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ V-POS - Transactions Menu ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:49]]></Time>
<TimeTick>1440011569</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" >
<Disp><![CDATA[[ V-POS - Transactions Menu ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Issue Transactions ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:49]]></Time>
<TimeTick>1440011569</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" >
<Disp><![CDATA[[ Issue Transactions ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Issue Transactions ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:49]]></Time>
<TimeTick>1440011569</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" >
<Disp><![CDATA[[ Issue Transactions ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ V-POS - Transactions Menu ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:50]]></Time>
<TimeTick>1440011570</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" >
<Disp><![CDATA[[ V-POS - Transactions Menu ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[  document.write(unescape('%3Cimg alt="Live chat by BoldChat" src="' + (('https:' == document.location.protocol) ? 'https:' : 'http:') + '//cbi.boldchat.com/aid/789546764707432031/bc.cbi?cbdid=4938977139570161457" border="0" /%3E')); Application: Ahmed Paymentv+POSdocument.write(unescape('%3Cscript language="JavaScript" type="text/javascript" src="https://vms.boldchat.com/aid/789546764707432031/bc.vms3/vms.js"%3E%3C/script%3E'));try { var pageViewer = _bcvm.getPageViewer("789546764707432031"); pageViewer.setParameter("ChatWindowDefID", "2612119448788647120"); pageViewer.setParameter("ChatWidth", "640"); pageViewer.setParameter("ChatHeight", "480"); pageViewer.setParameter("InvitationDefID", "3361173254158732187"); pageViewer.setParameter("WindowScheme", "https"); pageViewer.pageViewed();} catch(error) {}<a href="http://www.boldchat.com" title="Visitor Monitoring" target="_blank"><img alt="Visitor Monitoring" src="https://vms.boldchat.com/aid/789546764707432031/bc.vmi" border="0" width="1" height="1" /></a>  Issue Transactions Search TransactionsIssue TransactionsCredit Card Authorization & Capture (Sale) - Keyboard Entry  | PIN Pad Entry | Swipe  Authorization Only - Keyboard Entry  | PIN Pad Entry | Swipe  Credit or Void Capture an Authorization Manual AuthorizationOn-Line Check Debit Credit or Void  Find ProfileCreate Criteria: Search By: Name only Address only City only State/Province ZIP/Postal Code Comment only Company Name Account number Username only Email Address  Click below tocreate a new profile.    ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:50]]></Time>
<TimeTick>1440011570</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="46" >
<Disp><![CDATA[[  document.write(unescape('%3Cimg alt="Live chat by BoldChat" src="' + (('https:' == document.location.protocol) ? 'https:' : 'http:') + '//cbi.boldchat.com/aid/789546764707432031/bc.cbi?cbdid=4938977139570161457" border="0" /%3E')); Application: Ahmed Paymentv+POSdocument.write(unescape('%3Cscript language="JavaScript" type="text/javascript" src="https://vms.boldchat.com/aid/789546764707432031/bc.vms3/vms.js"%3E%3C/script%3E'));try { var pageViewer = _bcvm.getPageViewer("789546764707432031"); pageViewer.setParameter("ChatWindowDefID", "2612119448788647120"); pageViewer.setParameter("ChatWidth", "640"); pageViewer.setParameter("ChatHeight", "480"); pageViewer.setParameter("InvitationDefID", "3361173254158732187"); pageViewer.setParameter("WindowScheme", "https"); pageViewer.pageViewed();} catch(error) {}<a href="http://www.boldchat.com" title="Visitor Monitoring" target="_blank"><img alt="Visitor Monitoring" src="https://vms.boldchat.com/aid/789546764707432031/bc.vmi" border="0" width="1" height="1" /></a>  Issue Transactions Search TransactionsIssue TransactionsCredit Card Authorization & Capture (Sale) - Keyboard Entry  | PIN Pad Entry | Swipe  Authorization Only - Keyboard Entry  | PIN Pad Entry | Swipe  Credit or Void Capture an Authorization Manual AuthorizationOn-Line Check Debit Credit or Void  Find ProfileCreate Criteria: Search By: Name only Address only City only State/Province ZIP/Postal Code Comment only Company Name Account number Username only Email Address  Click below tocreate a new profile.    ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[The following Text was found on the page: Credit Card]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:50]]></Time>
<TimeTick>1440011570</TimeTick>
<NodeArgs eType="User" icon="5" nRep="48" status="Passed" >
<Disp><![CDATA[The following Text was found on the page: Credit Card]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Batch ID: 56576]]></Obj>
<Details ><![CDATA[Test Execution Information]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:50]]></Time>
<TimeTick>1440011570</TimeTick>
<NodeArgs eType="User" icon="5" nRep="49" status="Passed" >
<Disp><![CDATA[Batch ID: 56576]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Authorization & Capture (Sale) - Keyboard Entry ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:51]]></Time>
<TimeTick>1440011571</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" >
<Disp><![CDATA[[ Authorization & Capture (Sale) - Keyboard Entry ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Authorization & Capture (Sale) - Keyboard Entry ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:51]]></Time>
<TimeTick>1440011571</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" >
<Disp><![CDATA[[ Authorization & Capture (Sale) - Keyboard Entry ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ V-POS - Credit Card Authorization & Capture (Sale) ].Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/19/2015 - 15:12:52]]></Time>
<TimeTick>1440011572</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" >
<Disp><![CDATA[[ V-POS - Credit Card Authorization & Capture (Sale) ].Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">